### ISSUE TITLE
Tame codecov

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/Basilisk-node#109]
- builds shouldn't fail because of it
- hide warning on lines in PR

**Comment by enthusiastmartin** [comment]
There is a possibility to add codecov yaml config file. Acala's example:

```
coverage:
  precision: 2
  round: down 
  range: "70...100"
  status:                        # this controls whether a pull request will be blocked by a decrease in coverage
    # Learn more at https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 5%            # allows coverage to drop by up to the percent noted and still post a success status
        #informational: true     # If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified
    patch: 
      default:
        threshold: 5%            # allows coverage to drop by up to the percent noted and still post a success status
        #informational: true     # If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified
    changes: 
      default:
        threshold: 5%            # allows coverage to drop by up to the percent noted and still post a success status
        #informational: true     # If true is specified the resulting status will pass no matter what the coverage is or what other settings are specifie
```
