### ISSUE TITLE
Bug: Docker image is not working

### ISSUE THREAD

**Issue by nazar-pc** [galacticcouncil/Basilisk-node#210]
### Description
Trying to run archival node with following docker-compose.yml:
```yml
version: '2'

services:
  basilisk:
    image: galacticcouncil/hydra-dx
    ports:
      - 19954:9944
    volumes:
      - ./basilisk:/data
    command: [
      "hydra-dx",
      "--base-path", "/data",
      "--chain", "basilisk",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
    ]
```

### Expected Behavior
Node runs properly

### Actual Behavior
```
hydra-dx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by hydra-dx)
```

My host OS is Ubuntu 21.10 with GLibc 2.33.

### Context
Trying to run archival node to pull Basilisk blocks to later archive onto Subspace testnet
